apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices-demo-staging
commonLabels:
  variant: staging

resources:
  - namespace.yaml
  - ../base

images:
  - name: cartservice
    newName: registry.digitalocean.com/do-microserv-demo/cartservice
    newTag: 1.0.0
  - name: checkoutservice
    newName: registry.digitalocean.com/do-microserv-demo/checkoutservice
    newTag: 1.0.0
  - name: currencyservice
    newName: registry.digitalocean.com/do-microserv-demo/currencyservice
    newTag: 1.0.0
  - name: emailservice
    newName: registry.digitalocean.com/do-microserv-demo/emailservice
    newTag: 1.0.0
  - name: frontend
    newName: registry.digitalocean.com/do-microserv-demo/frontend
    newTag: 1.0.0
  - name: paymentservice
    newName: registry.digitalocean.com/do-microserv-demo/paymentservice
    newTag: 1.0.0
  - name: productcatalogservice
    newName: registry.digitalocean.com/do-microserv-demo/productcatalogservice
    newTag: 1.0.0
  - name: recommendationservice
    newName: registry.digitalocean.com/do-microserv-demo/recommendationservice
    newTag: 1.0.0
  - name: shippingservice
    newName: registry.digitalocean.com/do-microserv-demo/shippingservice
    newTag: 1.0.0

replicas:
  - name: cartservice
    count: 2
  - name: checkoutservice
    count: 2
  - name: currencyservice
    count: 2
  - name: emailservice
    count: 2
  - name: frontend
    count: 2
  - name: paymentservice
    count: 2
  - name: productcatalogservice
    count: 2
  - name: recommendationservice
    count: 2
  - name: shippingservice
    count: 2
